apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: possum-python 
  janus-idp.io/tekton: possum-python
  backstage.io/kubernetes-id: possum-python
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: possum-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  